<?php

namespace Database\Seeders;

use App\Models\EcommerceItem;
use App\Models\Category;
use App\Models\Brand;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MockDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Electronics (1-10)
            ['id' => 1, 'item_code' => "P-1", 'item_name' => "Wireless Headphones Pro", 'category_name' => "Electronics", 'brand_name' => "Sony", 'price' => 120, 'stock_quantity' => 45, 'description' => "Professional grade wireless headphones with noise cancellation.", 'images' => ["https://picsum.photos/seed/p1/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 2, 'item_code' => "P-2", 'item_name' => "Smartphone Ultra X", 'category_name' => "Electronics", 'brand_name' => "Samsung", 'price' => 899, 'stock_quantity' => 20, 'description' => "Latest flagship smartphone with stunning display and camera.", 'images' => ["https://picsum.photos/seed/p2/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 3, 'item_code' => "P-3", 'item_name' => "4K Smart TV 55\"", 'category_name' => "Electronics", 'brand_name' => "LG", 'price' => 650, 'stock_quantity' => 15, 'description' => "Immersive 4K viewing experience with smart features.", 'images' => ["https://picsum.photos/seed/p3/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 4, 'item_code' => "P-4", 'item_name' => "Gaming Laptop RTX", 'category_name' => "Electronics", 'brand_name' => "Asus", 'price' => 1500, 'stock_quantity' => 10, 'description' => "High-performance gaming laptop with RTX graphics.", 'images' => ["https://picsum.photos/seed/p4/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 5, 'item_code' => "P-5", 'item_name' => "Bluetooth Speaker Max", 'category_name' => "Electronics", 'brand_name' => "JBL", 'price' => 90, 'stock_quantity' => 50, 'description' => "Portable speaker with deep bass and clear sound.", 'images' => ["https://picsum.photos/seed/p5/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 6, 'item_code' => "P-6", 'item_name' => "Wireless Charger Pad", 'category_name' => "Electronics", 'brand_name' => "Anker", 'price' => 30, 'stock_quantity' => 100, 'description' => "Fast wireless charging for all your compatible devices.", 'images' => ["https://picsum.photos/seed/p6/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 7, 'item_code' => "P-7", 'item_name' => "Tablet Pro 11", 'category_name' => "Electronics", 'brand_name' => "Apple", 'price' => 999, 'stock_quantity' => 12, 'description' => "Powerful tablet for professionals and creatives.", 'images' => ["https://picsum.photos/seed/p7/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 8, 'item_code' => "P-8", 'item_name' => "Smartwatch Fit", 'category_name' => "Electronics", 'brand_name' => "Huawei", 'price' => 220, 'stock_quantity' => 30, 'description' => "Advanced fitness tracking and smart notifications.", 'images' => ["https://picsum.photos/seed/p8/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 9, 'item_code' => "P-9", 'item_name' => "Noise Cancelling Earbuds", 'category_name' => "Electronics", 'brand_name' => "Sony", 'price' => 199, 'stock_quantity' => 40, 'description' => "Compact earbuds with industry-leading noise cancellation.", 'images' => ["https://picsum.photos/seed/p9/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 10, 'item_code' => "P-10", 'item_name' => "Portable SSD 1TB", 'category_name' => "Electronics", 'brand_name' => "Samsung", 'price' => 140, 'stock_quantity' => 60, 'description' => "Secure and fast portable storage for your data.", 'images' => ["https://picsum.photos/seed/p10/800/800"], 'is_visible' => true, 'part_number' => ""],

            // Fashion (11-20)
            ['id' => 11, 'item_code' => "P-11", 'item_name' => "Men's Casual Jacket", 'category_name' => "Fashion", 'brand_name' => "Zara", 'price' => 80, 'stock_quantity' => 25, 'description' => "Stylish and comfortable jacket for casual outings.", 'images' => ["https://picsum.photos/seed/p11/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 12, 'item_code' => "P-12", 'item_name' => "Women's Summer Dress", 'category_name' => "Fashion", 'brand_name' => "H&M", 'price' => 45, 'stock_quantity' => 35, 'description' => "Breezy and elegant dress for the summer season.", 'images' => ["https://picsum.photos/seed/p12/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 13, 'item_code' => "P-13", 'item_name' => "Classic Denim Jeans", 'category_name' => "Fashion", 'brand_name' => "Levi's", 'price' => 70, 'stock_quantity' => 50, 'description' => "Durable and timeless denim jeans for everyday wear.", 'images' => ["https://picsum.photos/seed/p13/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 14, 'item_code' => "P-14", 'item_name' => "Cotton T-Shirt", 'category_name' => "Fashion", 'brand_name' => "Uniqlo", 'price' => 20, 'stock_quantity' => 100, 'description' => "Soft and breathable cotton t-shirt in various colors.", 'images' => ["https://picsum.photos/seed/p14/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 15, 'item_code' => "P-15", 'item_name' => "Formal Suit Set", 'category_name' => "Fashion", 'brand_name' => "Zara", 'price' => 200, 'stock_quantity' => 15, 'description' => "Premium formal suit set for special occasions.", 'images' => ["https://picsum.photos/seed/p15/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 16, 'item_code' => "P-16", 'item_name' => "Winter Hoodie", 'category_name' => "Fashion", 'brand_name' => "Nike", 'price' => 60, 'stock_quantity' => 40, 'description' => "Warm and cozy hoodie for the winter months.", 'images' => ["https://picsum.photos/seed/p16/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 17, 'item_code' => "P-17", 'item_name' => "Women's Blazer", 'category_name' => "Fashion", 'brand_name' => "Mango", 'price' => 90, 'stock_quantity' => 20, 'description' => "Chic blazer to elevate any professional or casual outfit.", 'images' => ["https://picsum.photos/seed/p17/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 18, 'item_code' => "P-18", 'item_name' => "Athletic Shorts", 'category_name' => "Fashion", 'brand_name' => "Adidas", 'price' => 35, 'stock_quantity' => 60, 'description' => "High-performance shorts for various athletic activities.", 'images' => ["https://picsum.photos/seed/p18/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 19, 'item_code' => "P-19", 'item_name' => "Slim Fit Shirt", 'category_name' => "Fashion", 'brand_name' => "Zara", 'price' => 40, 'stock_quantity' => 45, 'description' => "Modern slim fit shirt for a sharp and polished look.", 'images' => ["https://picsum.photos/seed/p19/800/800"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 20, 'item_code' => "P-20", 'item_name' => "Classic Polo Shirt", 'category_name' => "Fashion", 'brand_name' => "Lacoste", 'price' => 65, 'stock_quantity' => 30, 'description' => "Iconic polo shirt with a classic and comfortable design.", 'images' => ["https://picsum.photos/seed/p20/800/800"], 'is_visible' => true, 'part_number' => ""],

            // Bags (21-30)
            ['id' => 21, 'item_code' => "P-21", 'item_name' => "Travel Backpack Pro", 'category_name' => "Bags", 'brand_name' => "North Face", 'price' => 120, 'stock_quantity' => 25, 'description' => "Rugged and spacious backpack for your travel adventures.", 'images' => ["https://picsum.photos/seed/p21/800/800"], 'is_visible' => true, 'part_number' => "Backpack"],
            ['id' => 22, 'item_code' => "P-22", 'item_name' => "Laptop Bag Slim", 'category_name' => "Bags", 'brand_name' => "Samsonite", 'price' => 70, 'stock_quantity' => 40, 'description' => "Sleek and protective bag for your laptop and essentials.", 'images' => ["https://picsum.photos/seed/p22/800/800"], 'is_visible' => true, 'part_number' => "Laptop Bag"],
            ['id' => 23, 'item_code' => "P-23", 'item_name' => "Leather Handbag", 'category_name' => "Bags", 'brand_name' => "Gucci", 'price' => 450, 'stock_quantity' => 10, 'description' => "Luxury leather handbag with elegant craftsmanship.", 'images' => ["https://picsum.photos/seed/p23/800/800"], 'is_visible' => true, 'part_number' => "Handbag"],
            ['id' => 24, 'item_code' => "P-24", 'item_name' => "Messenger Bag Urban", 'category_name' => "Bags", 'brand_name' => "Fossil", 'price' => 110, 'stock_quantity' => 20, 'description' => "Versatile messenger bag for your daily urban commute.", 'images' => ["https://picsum.photos/seed/p24/800/800"], 'is_visible' => true, 'part_number' => "Messenger Bag"],
            ['id' => 25, 'item_code' => "P-25", 'item_name' => "School Backpack", 'category_name' => "Bags", 'brand_name' => "Nike", 'price' => 50, 'stock_quantity' => 60, 'description' => "Durable and stylish backpack for school and everyday use.", 'images' => ["https://picsum.photos/seed/p25/800/800"], 'is_visible' => true, 'part_number' => "Backpack"],
            ['id' => 26, 'item_code' => "P-26", 'item_name' => "Mini Crossbody Bag", 'category_name' => "Bags", 'brand_name' => "Coach", 'price' => 180, 'stock_quantity' => 15, 'description' => "Compact and chic crossbody bag for your essentials.", 'images' => ["https://picsum.photos/seed/p26/800/800"], 'is_visible' => true, 'part_number' => "Handbag"],
            ['id' => 27, 'item_code' => "P-27", 'item_name' => "Gym Duffel Bag", 'category_name' => "Bags", 'brand_name' => "Adidas", 'price' => 60, 'stock_quantity' => 30, 'description' => "Spacious and functional duffel bag for your gym gear.", 'images' => ["https://picsum.photos/seed/p27/800/800"], 'is_visible' => true, 'part_number' => "Travel Bag"],
            ['id' => 28, 'item_code' => "P-28", 'item_name' => "Travel Suitcase", 'category_name' => "Bags", 'brand_name' => "Samsonite", 'price' => 220, 'stock_quantity' => 12, 'description' => "Durable and easy-to-maneuver suitcase for your travels.", 'images' => ["https://picsum.photos/seed/p28/800/800"], 'is_visible' => true, 'part_number' => "Travel Bag"],
            ['id' => 29, 'item_code' => "P-29", 'item_name' => "Vintage Canvas Bag", 'category_name' => "Bags", 'brand_name' => "Fossil", 'price' => 95, 'stock_quantity' => 25, 'description' => "Classic canvas bag with a vintage-inspired design.", 'images' => ["https://picsum.photos/seed/p29/800/800"], 'is_visible' => true, 'part_number' => "Messenger Bag"],
            ['id' => 30, 'item_code' => "P-30", 'item_name' => "Premium Leather Backpack", 'category_name' => "Bags", 'brand_name' => "Coach", 'price' => 320, 'stock_quantity' => 10, 'description' => "High-quality leather backpack for a sophisticated look.", 'images' => ["https://picsum.photos/seed/p30/800/800"], 'is_visible' => true, 'part_number' => "Backpack"],

            // Shoes (31-40)
            ['id' => 31, 'item_code' => "P-31", 'item_name' => "Running Shoes Pro", 'category_name' => "Shoes", 'brand_name' => "Nike", 'price' => 120, 'stock_quantity' => 40, 'description' => "Lightweight running shoes designed for speed and comfort.", 'images' => ["https://picsum.photos/seed/p31/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 32, 'item_code' => "P-32", 'item_name' => "Classic Sneakers", 'category_name' => "Shoes", 'brand_name' => "Adidas", 'price' => 95, 'stock_quantity' => 50, 'description' => "Stylish everyday sneakers with durable rubber sole.", 'images' => ["https://picsum.photos/seed/p32/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 33, 'item_code' => "P-33", 'item_name' => "Leather Formal Shoes", 'category_name' => "Shoes", 'brand_name' => "Clarks", 'price' => 140, 'stock_quantity' => 20, 'description' => "Premium leather shoes perfect for formal occasions.", 'images' => ["https://picsum.photos/seed/p33/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 34, 'item_code' => "P-34", 'item_name' => "Basketball Sneakers", 'category_name' => "Shoes", 'brand_name' => "Jordan", 'price' => 180, 'stock_quantity' => 15, 'description' => "High-performance sneakers built for basketball players.", 'images' => ["https://picsum.photos/seed/p34/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 35, 'item_code' => "P-35", 'item_name' => "Trail Hiking Boots", 'category_name' => "Shoes", 'brand_name' => "Timberland", 'price' => 160, 'stock_quantity' => 25, 'description' => "Rugged hiking boots designed for outdoor adventures.", 'images' => ["https://picsum.photos/seed/p35/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 36, 'item_code' => "P-36", 'item_name' => "Slip On Casual Shoes", 'category_name' => "Shoes", 'brand_name' => "Vans", 'price' => 65, 'stock_quantity' => 60, 'description' => "Comfortable slip-on shoes perfect for casual wear.", 'images' => ["https://picsum.photos/seed/p36/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 37, 'item_code' => "P-37", 'item_name' => "Luxury Leather Loafers", 'category_name' => "Shoes", 'brand_name' => "Gucci", 'price' => 420, 'stock_quantity' => 10, 'description' => "Elegant loafers crafted from premium leather.", 'images' => ["https://picsum.photos/seed/p37/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 38, 'item_code' => "P-38", 'item_name' => "Training Gym Shoes", 'category_name' => "Shoes", 'brand_name' => "Reebok", 'price' => 90, 'stock_quantity' => 35, 'description' => "Versatile gym shoes designed for all workouts.", 'images' => ["https://picsum.photos/seed/p38/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 39, 'item_code' => "P-39", 'item_name' => "Fashion Platform Sneakers", 'category_name' => "Shoes", 'brand_name' => "Puma", 'price' => 110, 'stock_quantity' => 30, 'description' => "Modern platform sneakers for trendy outfits.", 'images' => ["https://picsum.photos/seed/p39/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 40, 'item_code' => "P-40", 'item_name' => "Minimal White Sneakers", 'category_name' => "Shoes", 'brand_name' => "CommonProjects", 'price' => 350, 'stock_quantity' => 12, 'description' => "Minimalist luxury sneakers with sleek design.", 'images' => ["https://picsum.photos/seed/p40/600/600"], 'is_visible' => true, 'part_number' => ""],

            // Accessories (41-50)
            ['id' => 41, 'item_code' => "P-41", 'item_name' => "Luxury Wrist Watch", 'category_name' => "Accessories", 'brand_name' => "Rolex", 'price' => 8500, 'stock_quantity' => 5, 'description' => "Elegant luxury watch crafted with precision engineering.", 'images' => ["https://picsum.photos/seed/p41/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 42, 'item_code' => "P-42", 'item_name' => "Leather Wallet", 'category_name' => "Accessories", 'brand_name' => "Fossil", 'price' => 65, 'stock_quantity' => 45, 'description' => "Slim leather wallet with multiple card slots.", 'images' => ["https://picsum.photos/seed/p42/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 43, 'item_code' => "P-43", 'item_name' => "Designer Sunglasses", 'category_name' => "Accessories", 'brand_name' => "RayBan", 'price' => 140, 'stock_quantity' => 30, 'description' => "Classic sunglasses with UV protection.", 'images' => ["https://picsum.photos/seed/p43/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 44, 'item_code' => "P-44", 'item_name' => "Minimal Necklace", 'category_name' => "Accessories", 'brand_name' => "Pandora", 'price' => 90, 'stock_quantity' => 40, 'description' => "Elegant necklace perfect for everyday style.", 'images' => ["https://picsum.photos/seed/p44/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 45, 'item_code' => "P-45", 'item_name' => "Luxury Bracelet", 'category_name' => "Accessories", 'brand_name' => "Cartier", 'price' => 1200, 'stock_quantity' => 8, 'description' => "Premium bracelet crafted with luxury materials.", 'images' => ["https://picsum.photos/seed/p45/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 46, 'item_code' => "P-46", 'item_name' => "Baseball Cap", 'category_name' => "Accessories", 'brand_name' => "Nike", 'price' => 30, 'stock_quantity' => 100, 'description' => "Classic cap with breathable fabric.", 'images' => ["https://picsum.photos/seed/p46/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 47, 'item_code' => "P-47", 'item_name' => "Silk Scarf", 'category_name' => "Accessories", 'brand_name' => "Hermes", 'price' => 320, 'stock_quantity' => 15, 'description' => "Luxury silk scarf with elegant patterns.", 'images' => ["https://picsum.photos/seed/p47/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 48, 'item_code' => "P-48", 'item_name' => "Travel Belt", 'category_name' => "Accessories", 'brand_name' => "Levi's", 'price' => 45, 'stock_quantity' => 50, 'description' => "Durable leather belt for everyday wear.", 'images' => ["https://picsum.photos/seed/p48/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 49, 'item_code' => "P-49", 'item_name' => "Smart Ring Tracker", 'category_name' => "Accessories", 'brand_name' => "Oura", 'price' => 299, 'stock_quantity' => 20, 'description' => "Smart ring that tracks health and sleep data.", 'images' => ["https://picsum.photos/seed/p49/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 50, 'item_code' => "P-50", 'item_name' => "Luxury Tie", 'category_name' => "Accessories", 'brand_name' => "Armani", 'price' => 120, 'stock_quantity' => 25, 'description' => "Silk tie perfect for business attire.", 'images' => ["https://picsum.photos/seed/p50/600/600"], 'is_visible' => true, 'part_number' => ""],

            // Home & Living (51-60)
            ['id' => 51, 'item_code' => "P-51", 'item_name' => "Modern Table Lamp", 'category_name' => "Home & Living", 'brand_name' => "IKEA", 'price' => 45, 'stock_quantity' => 40, 'description' => "Stylish lamp designed for modern interiors.", 'images' => ["https://picsum.photos/seed/p51/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 52, 'item_code' => "P-52", 'item_name' => "Luxury Sofa", 'category_name' => "Home & Living", 'brand_name' => "Ashley", 'price' => 850, 'stock_quantity' => 10, 'description' => "Comfortable sofa crafted with premium fabric.", 'images' => ["https://picsum.photos/seed/p52/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 53, 'item_code' => "P-53", 'item_name' => "Kitchen Mixer", 'category_name' => "Home & Living", 'brand_name' => "KitchenAid", 'price' => 399, 'stock_quantity' => 15, 'description' => "Professional kitchen mixer for baking lovers.", 'images' => ["https://picsum.photos/seed/p53/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 54, 'item_code' => "P-54", 'item_name' => "Ceramic Dinner Set", 'category_name' => "Home & Living", 'brand_name' => "Corelle", 'price' => 120, 'stock_quantity' => 25, 'description' => "Elegant dinnerware set for modern kitchens.", 'images' => ["https://picsum.photos/seed/p54/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 55, 'item_code' => "P-55", 'item_name' => "Memory Foam Pillow", 'category_name' => "Home & Living", 'brand_name' => "Tempur", 'price' => 75, 'stock_quantity' => 50, 'description' => "Ergonomic pillow designed for better sleep.", 'images' => ["https://picsum.photos/seed/p55/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 56, 'item_code' => "P-56", 'item_name' => "Decorative Wall Art", 'category_name' => "Home & Living", 'brand_name' => "UrbanDecor", 'price' => 95, 'stock_quantity' => 20, 'description' => "Modern artwork perfect for living room decor.", 'images' => ["https://picsum.photos/seed/p56/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 57, 'item_code' => "P-57", 'item_name' => "Wood Coffee Table", 'category_name' => "Home & Living", 'brand_name' => "Wayfair", 'price' => 250, 'stock_quantity' => 12, 'description' => "Solid wood coffee table with minimalist style.", 'images' => ["https://picsum.photos/seed/p57/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 58, 'item_code' => "P-58", 'item_name' => "Luxury Bed Sheets", 'category_name' => "Home & Living", 'brand_name' => "Brooklinen", 'price' => 140, 'stock_quantity' => 30, 'description' => "Soft premium cotton bed sheets.", 'images' => ["https://picsum.photos/seed/p58/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 59, 'item_code' => "P-59", 'item_name' => "Aroma Diffuser", 'category_name' => "Home & Living", 'brand_name' => "Muji", 'price' => 60, 'stock_quantity' => 45, 'description' => "Essential oil diffuser with relaxing aroma.", 'images' => ["https://picsum.photos/seed/p59/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 60, 'item_code' => "P-60", 'item_name' => "Minimal Bookshelf", 'category_name' => "Home & Living", 'brand_name' => "IKEA", 'price' => 110, 'stock_quantity' => 20, 'description' => "Simple bookshelf for modern homes.", 'images' => ["https://picsum.photos/seed/p60/600/600"], 'is_visible' => true, 'part_number' => ""],

            // Beauty (61-70)
            ['id' => 61, 'item_code' => "P-61", 'item_name' => "Luxury Perfume", 'category_name' => "Beauty", 'brand_name' => "Chanel", 'price' => 150, 'stock_quantity' => 25, 'description' => "Elegant fragrance designed for sophistication.", 'images' => ["https://picsum.photos/seed/p61/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 62, 'item_code' => "P-62", 'item_name' => "Moisturizing Face Cream", 'category_name' => "Beauty", 'brand_name' => "Clinique", 'price' => 55, 'stock_quantity' => 50, 'description' => "Hydrating face cream for smooth skin.", 'images' => ["https://picsum.photos/seed/p62/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 63, 'item_code' => "P-63", 'item_name' => "Professional Makeup Kit", 'category_name' => "Beauty", 'brand_name' => "MAC", 'price' => 120, 'stock_quantity' => 30, 'description' => "Complete makeup kit for professional artists.", 'images' => ["https://picsum.photos/seed/p63/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 64, 'item_code' => "P-64", 'item_name' => "Hair Styling Dryer", 'category_name' => "Beauty", 'brand_name' => "Dyson", 'price' => 420, 'stock_quantity' => 15, 'description' => "High performance hair dryer with fast drying.", 'images' => ["https://picsum.photos/seed/p64/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 65, 'item_code' => "P-65", 'item_name' => "Organic Shampoo", 'category_name' => "Beauty", 'brand_name' => "Aveda", 'price' => 35, 'stock_quantity' => 100, 'description' => "Natural shampoo with nourishing ingredients.", 'images' => ["https://picsum.photos/seed/p65/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 66, 'item_code' => "P-66", 'item_name' => "Vitamin C Serum", 'category_name' => "Beauty", 'brand_name' => "TheOrdinary", 'price' => 25, 'stock_quantity' => 80, 'description' => "Brightening serum for radiant skin.", 'images' => ["https://picsum.photos/seed/p66/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 67, 'item_code' => "P-67", 'item_name' => "Luxury Lipstick", 'category_name' => "Beauty", 'brand_name' => "Dior", 'price' => 45, 'stock_quantity' => 60, 'description' => "Long lasting lipstick with vibrant colors.", 'images' => ["https://picsum.photos/seed/p67/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 68, 'item_code' => "P-68", 'item_name' => "Facial Cleansing Brush", 'category_name' => "Beauty", 'brand_name' => "Foreo", 'price' => 120, 'stock_quantity' => 20, 'description' => "Deep cleansing brush for healthy skin.", 'images' => ["https://picsum.photos/seed/p68/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 69, 'item_code' => "P-69", 'item_name' => "Nail Care Set", 'category_name' => "Beauty", 'brand_name' => "OPI", 'price' => 40, 'stock_quantity' => 40, 'description' => "Complete manicure set for nail care.", 'images' => ["https://picsum.photos/seed/p69/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 70, 'item_code' => "P-70", 'item_name' => "Premium Face Mask", 'category_name' => "Beauty", 'brand_name' => "Lancome", 'price' => 60, 'stock_quantity' => 35, 'description' => "Luxury skincare mask for hydration.", 'images' => ["https://picsum.photos/seed/p70/600/600"], 'is_visible' => true, 'part_number' => ""],

            // Sports (71-80)
            ['id' => 71, 'item_code' => "P-71", 'item_name' => "Professional Basketball", 'category_name' => "Sports", 'brand_name' => "Spalding", 'price' => 45, 'stock_quantity' => 50, 'description' => "Official size basketball for indoor and outdoor games.", 'images' => ["https://picsum.photos/seed/p71/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 72, 'item_code' => "P-72", 'item_name' => "Yoga Mat Pro", 'category_name' => "Sports", 'brand_name' => "Lululemon", 'price' => 80, 'stock_quantity' => 40, 'description' => "Non slip yoga mat designed for stability.", 'images' => ["https://picsum.photos/seed/p72/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 73, 'item_code' => "P-73", 'item_name' => "Adjustable Dumbbells", 'category_name' => "Sports", 'brand_name' => "Bowflex", 'price' => 350, 'stock_quantity' => 12, 'description' => "Compact adjustable dumbbells for home gym.", 'images' => ["https://picsum.photos/seed/p73/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 74, 'item_code' => "P-74", 'item_name' => "Football Training Ball", 'category_name' => "Sports", 'brand_name' => "Nike", 'price' => 35, 'stock_quantity' => 60, 'description' => "Durable football for training sessions.", 'images' => ["https://picsum.photos/seed/p74/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 75, 'item_code' => "P-75", 'item_name' => "Tennis Racket", 'category_name' => "Sports", 'brand_name' => "Wilson", 'price' => 120, 'stock_quantity' => 25, 'description' => "Professional tennis racket for competitive play.", 'images' => ["https://picsum.photos/seed/p75/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 76, 'item_code' => "P-76", 'item_name' => "Cycling Helmet", 'category_name' => "Sports", 'brand_name' => "Giro", 'price' => 90, 'stock_quantity' => 30, 'description' => "Lightweight helmet designed for safe cycling.", 'images' => ["https://picsum.photos/seed/p76/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 77, 'item_code' => "P-77", 'item_name' => "Fitness Resistance Bands", 'category_name' => "Sports", 'brand_name' => "TheraBand", 'price' => 25, 'stock_quantity' => 80, 'description' => "Resistance bands for strength training.", 'images' => ["https://picsum.photos/seed/p77/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 78, 'item_code' => "P-78", 'item_name' => "Professional Boxing Gloves", 'category_name' => "Sports", 'brand_name' => "Everlast", 'price' => 75, 'stock_quantity' => 20, 'description' => "Durable boxing gloves for intense training.", 'images' => ["https://picsum.photos/seed/p78/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 79, 'item_code' => "P-79", 'item_name' => "Running Smart Tracker", 'category_name' => "Sports", 'brand_name' => "Garmin", 'price' => 220, 'stock_quantity' => 15, 'description' => "Advanced running watch with GPS tracking.", 'images' => ["https://picsum.photos/seed/p79/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 80, 'item_code' => "P-80", 'item_name' => "Gym Water Bottle", 'category_name' => "Sports", 'brand_name' => "HydroFlask", 'price' => 30, 'stock_quantity' => 100, 'description' => "Insulated water bottle for workouts.", 'images' => ["https://picsum.photos/seed/p80/600/600"], 'is_visible' => true, 'part_number' => ""],

            // Gadgets (81-90)
            ['id' => 81, 'item_code' => "P-81", 'item_name' => "Drone Camera 4K", 'category_name' => "Gadgets", 'brand_name' => "DJI", 'price' => 799, 'stock_quantity' => 10, 'description' => "Professional drone with 4K camera stabilization.", 'images' => ["https://picsum.photos/seed/p81/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 82, 'item_code' => "P-82", 'item_name' => "VR Headset", 'category_name' => "Gadgets", 'brand_name' => "Meta", 'price' => 399, 'stock_quantity' => 15, 'description' => "Immersive virtual reality headset for gaming.", 'images' => ["https://picsum.photos/seed/p82/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 83, 'item_code' => "P-83", 'item_name' => "Smart Home Hub", 'category_name' => "Gadgets", 'brand_name' => "Google", 'price' => 120, 'stock_quantity' => 25, 'description' => "Control smart home devices from one hub.", 'images' => ["https://picsum.photos/seed/p83/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 84, 'item_code' => "P-84", 'item_name' => "Portable Projector", 'category_name' => "Gadgets", 'brand_name' => "Anker", 'price' => 350, 'stock_quantity' => 12, 'description' => "Compact projector for movies anywhere.", 'images' => ["https://picsum.photos/seed/p84/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 85, 'item_code' => "P-85", 'item_name' => "Wireless Keyboard", 'category_name' => "Gadgets", 'brand_name' => "Logitech", 'price' => 70, 'stock_quantity' => 45, 'description' => "Slim wireless keyboard with long battery life.", 'images' => ["https://picsum.photos/seed/p85/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 86, 'item_code' => "P-86", 'item_name' => "Mechanical Gaming Mouse", 'category_name' => "Gadgets", 'brand_name' => "Razer", 'price' => 90, 'stock_quantity' => 40, 'description' => "High precision gaming mouse with RGB.", 'images' => ["https://picsum.photos/seed/p86/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 87, 'item_code' => "P-87", 'item_name' => "Smart Light Bulb", 'category_name' => "Gadgets", 'brand_name' => "PhilipsHue", 'price' => 45, 'stock_quantity' => 100, 'description' => "Smart bulb with customizable colors.", 'images' => ["https://picsum.photos/seed/p87/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 88, 'item_code' => "P-88", 'item_name' => "Noise Cancelling Mic", 'category_name' => "Gadgets", 'brand_name' => "Blue", 'price' => 150, 'stock_quantity' => 20, 'description' => "Studio microphone for streaming.", 'images' => ["https://picsum.photos/seed/p88/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 89, 'item_code' => "P-89", 'item_name' => "Portable Power Bank", 'category_name' => "Gadgets", 'brand_name' => "Anker", 'price' => 60, 'stock_quantity' => 60, 'description' => "High capacity power bank for travel.", 'images' => ["https://picsum.photos/seed/p89/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 90, 'item_code' => "P-90", 'item_name' => "Smart Door Lock", 'category_name' => "Gadgets", 'brand_name' => "August", 'price' => 220, 'stock_quantity' => 15, 'description' => "Secure smart lock for modern homes.", 'images' => ["https://picsum.photos/seed/p90/600/600"], 'is_visible' => true, 'part_number' => ""],

            // Lifestyle (91-100)
            ['id' => 91, 'item_code' => "P-91", 'item_name' => "Luxury Travel Watch Case", 'category_name' => "Lifestyle", 'brand_name' => "Wolf", 'price' => 120, 'stock_quantity' => 20, 'description' => "Elegant case for protecting watches while traveling.", 'images' => ["https://picsum.photos/seed/p91/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 92, 'item_code' => "P-92", 'item_name' => "Premium Travel Organizer", 'category_name' => "Lifestyle", 'brand_name' => "Bellroy", 'price' => 85, 'stock_quantity' => 35, 'description' => "Organize cables, gadgets and essentials.", 'images' => ["https://picsum.photos/seed/p92/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 93, 'item_code' => "P-93", 'item_name' => "Minimal Desk Setup Kit", 'category_name' => "Lifestyle", 'brand_name' => "Groove", 'price' => 150, 'stock_quantity' => 15, 'description' => "Desk accessories for productivity.", 'images' => ["https://picsum.photos/seed/p93/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 94, 'item_code' => "P-94", 'item_name' => "Travel Coffee Maker", 'category_name' => "Lifestyle", 'brand_name' => "Wacaco", 'price' => 95, 'stock_quantity' => 25, 'description' => "Portable espresso maker for travel.", 'images' => ["https://picsum.photos/seed/p94/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 95, 'item_code' => "P-95", 'item_name' => "Luxury Notebook", 'category_name' => "Lifestyle", 'brand_name' => "Moleskine", 'price' => 30, 'stock_quantity' => 100, 'description' => "Premium notebook for journaling.", 'images' => ["https://picsum.photos/seed/p95/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 96, 'item_code' => "P-96", 'item_name' => "Premium Fountain Pen", 'category_name' => "Lifestyle", 'brand_name' => "Montblanc", 'price' => 420, 'stock_quantity' => 10, 'description' => "Luxury pen designed for professionals.", 'images' => ["https://picsum.photos/seed/p96/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 97, 'item_code' => "P-97", 'item_name' => "Smart Travel Mug", 'category_name' => "Lifestyle", 'brand_name' => "Ember", 'price' => 130, 'stock_quantity' => 40, 'description' => "Temperature controlled smart mug.", 'images' => ["https://picsum.photos/seed/p97/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 98, 'item_code' => "P-98", 'item_name' => "Portable Picnic Set", 'category_name' => "Lifestyle", 'brand_name' => "NatureGear", 'price' => 110, 'stock_quantity' => 20, 'description' => "Complete picnic set for outdoor trips.", 'images' => ["https://picsum.photos/seed/p98/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 99, 'item_code' => "P-99", 'item_name' => "Luxury Candle Set", 'category_name' => "Lifestyle", 'brand_name' => "Diptyque", 'price' => 95, 'stock_quantity' => 30, 'description' => "Premium scented candles for relaxation.", 'images' => ["https://picsum.photos/seed/p99/600/600"], 'is_visible' => true, 'part_number' => ""],
            ['id' => 100, 'item_code' => "P-100", 'item_name' => "Minimal Travel Backpack", 'category_name' => "Lifestyle", 'brand_name' => "Bellroy", 'price' => 180, 'stock_quantity' => 15, 'description' => "Modern travel backpack with smart storage.", 'images' => ["https://picsum.photos/seed/p100/600/600"], 'is_visible' => true, 'part_number' => ""],
        ];

        foreach ($products as $p) {
            // Find or create category
            $category = Category::where('name', $p['category_name'])
                ->orWhere('slug', Str::slug($p['category_name']))
                ->first();

            if (!$category) {
                $category = Category::create([
                    'name' => $p['category_name'],
                    'slug' => Str::slug($p['category_name'])
                ]);
            }

            // Find or create brand
            $brand = Brand::where('name', $p['brand_name'])
                ->orWhere('slug', Str::slug($p['brand_name']))
                ->first();

            if (!$brand) {
                $brand = Brand::create([
                    'name' => $p['brand_name'],
                    'slug' => Str::slug($p['brand_name'])
                ]);
            }

            // Create product
            EcommerceItem::updateOrCreate(
                ['item_code' => $p['item_code']],
                [
                    'item_name' => $p['item_name'],
                    'category_id' => $category->id,
                    'brand_id' => $brand->id,
                    'category_name' => $p['category_name'],
                    'brand_name' => $p['brand_name'],
                    'price' => $p['price'],
                    'stock_quantity' => $p['stock_quantity'],
                    'description' => $p['description'],
                    'images' => $p['images'],
                    'is_visible' => $p['is_visible'],
                    'part_number' => $p['part_number'],
                ]
            );
        }
    }
}
